spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    tomcat:
      max-idle: 5
      max-active: 10
      min-idle: 2
      initial-size: 5
      remove-abandoned: true
  data:
    rest:
      base-path: "/api"
